POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "prueba",
    "email": "pjr@prueba.com",
    "password": "12"
}



### login sin coneccion a BD

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "prueba 2",
    "email": "pjr@prueba.com",
    "password": "1234567"
}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBqckBnbWFpbC5jb20iLCJpZCI6MSwiaWF0IjoxNzMwNzU0MzgwLCJleHAiOjE3MzA3NTQ0NDB9.sEBOSFkDWFmGrGWhKHjGlnFnIoO5WTJELfT_ftJ42gA
